site_name: Terarium Help
site_author: Uncharted Software Inc.

copyright: Copyright &copy; 2024 Uncharted Software Inc.

theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.footer
    - content.code.copy
  logo_dark_mode: img/terarium-logo-dark.svg
  logo_light_mode: img/terarium-logo-light.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: terarium
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: img/terarium-icon.png
  font: false
  language: custom

plugins:
  - search: {}
  - glightbox: {}
  - macros: {}
  - print-site:
      enumerate_headings: false
      add_cover_page: true
      add_to_navigation: true
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/custom_banner.tpl"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DARPA-ASKEM/Terarium
      name: Terarium on GitHub
  product_name: Terarium
  build: core

markdown_extensions:
    admonition: {}
    attr_list: {}
    def_list: {}
    md_in_html: {}
    pymdownx.details: {}
    pymdownx.superfences: {}
    pymdownx.tabbed:
      alternate_style: true 
    pymdownx.keys: {}
    pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
    tables:

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - index.md
  - What's new: 
    - whats-new/index.md
  - Get started:
    - get-started/index.md
  - Gather modeling resources: modeling-resources/index.md
  - Manage workflows: workflows/index.md
  - Work with data: datasets/index.md
  - Work with models: 
    - models/index.md
    - Edit a model: models/edit-model.md
    - Extract a model from code: models/extract-code.md
    - Enrich model descriptions: models/enrich-descriptions.md
    - Stratify a model: models/stratify-model.md
    - Configure a model: models/configure-model.md
    - Simulate a model: models/simulate-model.md
    - Calibrate a model: models/calibrate-model.md
    - Create, calibrate, and simulate a model ensemble: models/model-ensemble.md
  - Save insights as notes: notes/index.md
  - Integrated subsystems:
    - subsystems/index.md
    - TDS: subsystems/TDS.md
    - AMR: subsystems/AMR.md
    - Knowledge extraction: subsystems/knowledge-extraction.md
    - Modeling: subsystems/modeling.md
    - Simulation: subsystems/simulation.md
  - Glossary: 
    - glossary/index.md