site_name: Terarium help
site_author: Uncharted Software Inc.

copyright: Copyright &copy; 2024 Uncharted Software Inc.

theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.tabs.link
  logo_dark_mode: img/terarium-logo-dark.svg
  logo_light_mode: img/terarium-logo-light.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: terarium
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: img/terarium-icon.png
  font: false
  language: custom

plugins:
  - search: {}
  - glightbox: {}
  - macros: {}
  - redirects:
      redirect_maps:
        # 'old.md': 'new.md'
        # 'old/file.md': 'new/file.md'
        # 'some_file.md': 'http://external.url.com/foobar'
  - print-site:
      enumerate_headings: false
      add_cover_page: true
      add_to_navigation: true
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/custom_banner.tpl"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DARPA-ASKEM/Terarium
      name: Terarium on GitHub
  product_name: Terarium
  build: core

markdown_extensions:
    admonition: {}
    attr_list: {}
    def_list: {}
    md_in_html: {}
    pymdownx.details: {}
    pymdownx.superfences: {}
    pymdownx.tabbed:
      alternate_style: true 
    pymdownx.keys: {}
    pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
    pymdownx.arithmatex:
      generic: true
    tables:

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 
    - index.md
  - Get started:
    - Using Terarium: get-started/using-terarium.md
    - "Tutorial: Recreate, modify, and simulate a model": get-started/example-workflow.md  
  - Gather modeling resources: upload-resources/index.md
  - Build a workflow graph: workflows/index.md
  - Review and transform data: 
    - datasets/index.md
    - Review and enrich a dataset: datasets/review-and-enrich-dataset.md
    - Transform dataset: datasets/transform-dataset.md
  - Modeling: 
    - modeling/index.md
    - Review and enrich a model: modeling/review-and-enrich-model.md
    - Create a model from equations: modeling/create-model-from-equations.md
    - Edit a model: modeling/edit-model.md
    - Stratify a model: modeling/stratify-model.md
    - Compare models: modeling/compare-models.md
  - Configuration and intervention:
    - config-and-intervention/index.md
    - Configure a model: config-and-intervention/configure-model.md
    - Validate a model configuration: config-and-intervention/validate-model-configuration.md
    - Create an intervention policy: config-and-intervention/create-intervention-policy.md
    - Optimize an intervention policy: config-and-intervention/optimize-intervention-policy.md
  - Simulation:
    - simulation/index.md
    - Simulate a model: simulation/simulate-model.md
    - Calibrate a model: simulation/calibrate-model.md
    - Simulate ensemble: simulation/simulate-ensemble.md
    - Calibrate ensemble: simulation/calibrate-ensemble.md
  - Annotate your work: notes/index.md
  - Integrated subsystems:
    - subsystems/index.md
    - TDS: subsystems/TDS.md
    - AMR: subsystems/AMR.md
    - Knowledge extraction: subsystems/knowledge-extraction.md
    - Modeling: subsystems/modeling.md
    - Simulation: subsystems/simulation.md
    - Beaker: subsystems/beaker.md
  - Glossary: 
    - glossary/index.md